name:                corridor-client
version:             0.1.0.0
github:              "fizruk/lambdaconf-2019-workshop"
license:             BSD3
author:              "Nikolai Kudasov"
maintainer:          "nickolay.kudasov@gmail.com"
copyright:           "2019 Nikolai Kudasov"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fizruk/lambdaconf-2019-workshop#readme>

dependencies:
- base >= 4.7 && < 5
- corridor
- miso

library:
  source-dirs: src

executables:
  corridor-client:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - corridor-client
